# Generated by Django 4.1 on 2022-09-14 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0002_borrower_added_on_borrower_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='borrower',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.borrower'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='book',
            name='library',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.library'),
        ),
        migrations.AlterField(
            model_name='library',
            name='librarian',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.librarian'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='book_returned_on',
            field=models.DateField(default=None),
        ),
    ]
