# Generated by Django 4.1 on 2022-09-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_alter_book_author_alter_book_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='library',
            name='librarian',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.librarian'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='book_returned_on',
            field=models.DateField(blank=True),
        ),
    ]
