# Generated by Django 4.1 on 2022-09-14 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_alter_book_author_alter_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='librarian',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.librarian'),
        ),
    ]
