# Generated by Django 4.1 on 2022-09-14 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_alter_library_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='librarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lmsapp.librarian'),
        ),
    ]
