# Generated by Django 4.1 on 2022-09-16 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0008_alter_book_borrower_alter_book_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='book_returned_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
